version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: "create-document:1:1,update-document:1:1"
    depends_on:
      - zookeeper
  documentservice:
    build: ./document-service
    links:
      - kafka
      - storageservice
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8081:8081"
  storageservice:
    build: ./storage-service
    environment:
      STORAGE_PATH: '/storage'
    links:
      - kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - type: bind
        source: ./file-storage/
        target: /storage
    ports:
      - "8082:8082"