kafka:
  topic:
    create: create-document
    update: update-document
    
spring:
  application:
    name: document-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS}
    schema-registry: ${SPRING_KAFKA_SCHEMA_REGISTRY}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    
server:
  port: 8081

feign:
  apis:
    document: http://${STORAGE_SERVICE_HOST}:${STORAGE_SERVICE_PORT}